[build]
builder = "NIXPACKS"

[deploy]
# Using 'backend' as the root directory. 
# This contains 'index.php' as the entry point and the 'api' folder.
root = "backend"

[nixpacks]
# Let nixpacks auto-detect everything
